### ISSUE TITLE
Respond with error messages

### ISSUE THREAD

**Issue by intenscia** [nickelc/modio-bot#1]
When a user performs an action that has no outcome, the modbot should return an error message so the user knows why.

~subscribe 123

"Only users with manage channels role can subscribe to games"

**Comment by nickelc** [comment]
A dispatch error handler is the way to go ([on_dispatch_error](https://docs.rs/serenity/0.5.13/serenity/framework/standard/struct.StandardFramework.html#method.on_dispatch_error)).

**Comment by intenscia** [comment]
Can an error be returned if two commands are made too close to one another? I changed the limit from 5 seconds to 1 second as well in #4

**Comment by nickelc** [comment]
yes, it's possible with [DispatchError::RateLimited](https://docs.rs/serenity/0.5.11/serenity/framework/standard/enum.DispatchError.html#variant.RateLimited).
