### ISSUE TITLE
More details for updates

### ISSUE THREAD

**Issue by intenscia** [nickelc/modio-bot#5]
Currently the updates are very light on:

"The mod has been edited"
"The primary file changed. link"

![aaa](https://i.imgur.com/bEvgLYU.png)

I believe the game icon and name should be included in either the header or the footer. 

For the primary file, either the new version or changelog should be included. Also instead of link, can you link the text? "The primary file [has changed](#) to v0.5.3. Changelog: ..."

For the mod has been edited, can you mention the fields changed? Not essential if not.

**Comment by nickelc** [comment]
> I believe the game icon and name should be included in either the header or the footer.

Footer vs. Header
![image](https://user-images.githubusercontent.com/2128532/57388931-85d92600-71b9-11e9-9392-9b44ccab5496.png)

> For the primary file, either the new version or changelog should be included.

![image](https://user-images.githubusercontent.com/2128532/57396806-85498b00-71cb-11e9-8e9b-6e7abcc83139.png)
or with optional fields
![image](https://user-images.githubusercontent.com/2128532/57403996-373c8380-71db-11e9-8ebf-25d9a9146154.png)

> For the mod has been edited, can you mention the fields changed? Not essential if not.

Not possible, there is no versioning of data.

**Comment by nickelc** [comment]
Footer vs. Header
![image](https://user-images.githubusercontent.com/2128532/57388931-85d92600-71b9-11e9-9392-9b44ccab5496.png)

**Comment by intenscia** [comment]
Internally we track the fields changed, but don't expose that via the API. I think the game name should be in the header and text should be structured like:

The primary file [has changed](#) to 0.5. Changelog:
`change #1`
`change #2`

Also "A new mod is available" I'm wondering if that should return something similar to the full mod details card? Since it's a pretty big event?

Other changes look great.

**Comment by nickelc** [comment]
![image](https://user-images.githubusercontent.com/2128532/57445562-eb2d2580-7252-11e9-9311-1f8c9eabe000.png)
