### ISSUE TITLE
Consistent mod updates presentation

### ISSUE THREAD

**Issue by intenscia** [nickelc/modio-bot#9]
At the moment "A new mod is available" includes the creator in the header, and does not mention the game. 

But "A mod has been updated" includes the game in the header and not the creator.

I think for consistency the game should always be in the header, and the creator is either linked in the description or in the footer

**Comment by nickelc** [comment]
I also removed the ratings, stats & date fields and set an image instead of a thumbnail.

![image](https://user-images.githubusercontent.com/2128532/57806250-08845700-775f-11e9-8c90-5981f47e59b7.png)

**Comment by intenscia** [comment]
Nice, should filesize or version be included?
